#!/usr/bin/env node
// Downloads the woff2 files for Sour Gummy and writes a local
// @font-face stylesheet, so the page makes no request to Google at runtime.
// Re-run with `npm run fonts` if the families ever change.
import { mkdir, writeFile } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Sour+Gummy:wdth,wght@100,100..900&display=swap';
const CHROME_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';
const OUT_DIR = new URL('../assets/fonts/', import.meta.url);

// Only these two subsets carry the characters the page actually uses.
const SUBSETS = [
  { name: 'latin', marker: 'U+0000-00FF' },
  { name: 'latin-ext', marker: 'U+0100-02BA' },
];

const field = (block, name) => new RegExp(`${name}: ([^;]+);`).exec(block)?.[1]?.trim();

const css = await fetch(CSS_URL, { headers: { 'User-Agent': CHROME_UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts answered ${r.status}`);
  return r.text();
});

await mkdir(OUT_DIR, { recursive: true });

const rules = [];
for (const block of css.split('@font-face').slice(1)) {
  const family = field(block, 'font-family')?.replaceAll("'", '');
  const weight = field(block, 'font-weight');
  const range = field(block, 'unicode-range') ?? '';
  const src = /url\((https:[^)]+)\)/.exec(block)?.[1];
  if (!family || !src) continue;

  const subset = SUBSETS.find((s) => range.includes(s.marker));
  if (!subset) continue;

  const file = `${family.toLowerCase().replaceAll(' ', '-')}-${subset.name}.woff2`;
  const bytes = Buffer.from(
    await fetch(src).then((r) => {
      if (!r.ok) throw new Error(`${src} answered ${r.status}`);
      return r.arrayBuffer();
    }),
  );
  await writeFile(new URL(file, OUT_DIR), bytes);
  console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} kB`);

  rules.push(`@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('./${file}') format('woff2');
  unicode-range: ${range};
}`);
}

if (rules.length === 0) throw new Error('No latin subsets found — the CSS format changed.');

await writeFile(
  new URL('fonts.css', OUT_DIR),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n${rules.join('\n')}\n`,
);
console.log(`\nWrote assets/fonts/fonts.css with ${rules.length} @font-face rules.`);
